### ISSUE TITLE
Make TestDogerelay.sol2 work

### ISSUE THREAD

**Issue by oscarguindzberg** [dogethereum/dogerelay#19]

**Comment by cat-j** [comment]
This test doesn't seem to be around anymore, has it been deprecated?

**Comment by oscarguindzberg** [comment]
@ismaelbej fixed this https://github.com/dogethereum/dogerelay/commit/3cdbe7272ccd3c06cb258e14ac38c1840ba6d155#diff-b31d369cdbbc13513ec8600060e17d32
