### ISSUE TITLE
Evaluate storing doge block as struct instead of as byte array

### ISSUE THREAD

**Issue by oscarguindzberg** [dogethereum/dogerelay#24]
- Do we save gas by doing that?
- is the code more readable?
- Should we discard merge mining data? a standard merge mining block has 700 bytes, where 620 bytes are merge mining info.

**Comment by cat-j** [comment]
Done. Tests took less gas to run. Merge mining data can probably be discarded as long as AuxPoW is checked **before** storing the block as a struct.
