### ISSUE TITLE
Look into security measures against falsifying _truebitClaimantAddress argument in storeBlockHeader

### ISSUE THREAD

**Issue by cat-j** [dogethereum/dogerelay#30]
- Problem: how do we know that the person whose address is being passed as `_truebitClaimantAddress` has authorised whoever is calling `storeBlockHeader` to use it?
- Possible solution 1: add a database of addresses authorised to send blocks
- Possible solution 2: add a digital signature system to DogeRelay so that `storeBlockHeader` requires the claimant's private DogeRelay key along with their public Ethereum address
- Maybe both solutions could work together

**Comment by oscarguindzberg** [comment]
solution 3: remove _truebitClaimantAddress parameter and use msg.origin instead.
solution 4: Use some sort of hierarchical deterministic wallet and make sure msg.orgin and _truebitClaimantAddress were generated from the same seed.

I like solution 3.

**Comment by oscarguindzberg** [comment]
We implemented solution 3.
