### ISSUE TITLE
Complete block difficulty adjustement code for doge testnet

### ISSUE THREAD

**Issue by oscarguindzberg** [dogethereum/dogerelay#4]
- Not working for doge testnet
- This code has bugs:
if (net == Network.TESTNET && m_getTimestamp(hashPrevBlock) - m_getTimestamp(blockSha256Hash) > 120) {
                newBits = 0x1e0fffff;
}
- Code should be:
if (net == Network.TESTNET && m_getTimestampOfBlockBeingAddedWhichIsNotInStorageYet(blockSha256Hash) - m_getTimestamp(hashPrevBlock) > 120) {
                newBits = 0x1e0fffff;
}
- Update tests so we can have some doge testnet blocks that took less than 120 seconds to mine too. Currently we only have sample doge testnet blocks that took more than 120 seconds.

**Comment by cat-j** [comment]
Also fixed!
